[package]
name = "appd-shell-apple"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
default = []
test-stubs = ["appd-bare/test-stubs", "appd-runtime/test-stubs"]

[dependencies]
appd-bare = { path = "../appd-bare", features = ["native"] }
appd-bundle = { path = "../appd-bundle" }
appd-runtime = { path = "../appd-runtime", features = ["native"] }
p256.workspace = true

[dev-dependencies]
rcgen = { workspace = true, features = ["pem"] }
tempfile.workspace = true

[lints]
workspace = true
