[package]
name = "appd-quickjs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
native = ["dep:openssl", "dep:tokio"]
test-stubs = ["native"]

[dependencies]
appd-vfs = { path = "../appd-vfs" }
node-fs = { path = "../node-fs" }
base64.workspace = true
flate2.workspace = true
libc.workspace = true
rquickjs.workspace = true
serde.workspace = true
serde_json.workspace = true
openssl = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true
time.workspace = true

[lints]
workspace = true
