[package]
name = "appd-bare"
links = "appd_bare"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
native = []
test-stubs = ["native"]

[dependencies]
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[build-dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true
time.workspace = true

[lints]
workspace = true
