[package]
name = "appd-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "appd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
appd-bundle = { path = "../appd-bundle" }
appd-target-pack = { path = "../appd-target-pack" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true
