[package]
name = "appd-shell-windows"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "appd-shell-windows"
path = "src/main.rs"

[features]
test-stubs = ["appd-quickjs/test-stubs", "appd-runtime/test-stubs"]

[target.'cfg(windows)'.dependencies]
anyhow.workspace = true
appd-quickjs = { path = "../appd-quickjs", features = ["native"] }
appd-bundle = { path = "../appd-bundle" }
appd-runtime = { path = "../appd-runtime", features = ["native"] }
base64.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
tao.workspace = true
webview2-com.workspace = true
windows.workspace = true
wry.workspace = true

[lints]
workspace = true
