[package]
name = "appd-shell-android"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "appd_shell_android"
crate-type = ["cdylib"]

[features]
default = []
test-stubs = ["appd-quickjs/test-stubs", "appd-runtime/test-stubs"]

[dependencies]
appd-quickjs = { path = "../appd-quickjs", features = ["native"] }
appd-bundle = { path = "../appd-bundle" }
appd-runtime = { path = "../appd-runtime", features = ["native"] }
jni.workspace = true

[lints]
workspace = true
