[package]
name = "appd-runtime"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
native = ["dep:appd-quickjs", "dep:appd-bundle", "appd-quickjs/native"]
test-stubs = ["native", "appd-quickjs/test-stubs"]

[dependencies]
appd-quickjs = { path = "../appd-quickjs", optional = true }
appd-bundle = { path = "../appd-bundle", optional = true }
rcgen = { workspace = true, features = ["pem", "x509-parser"] }
thiserror.workspace = true
time.workspace = true
x509-parser = { workspace = true, features = ["verify"] }

[dev-dependencies]
openssl.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
