[package]
name = "appd-runtime"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
native = ["dep:appd-bare", "dep:appd-bundle", "appd-bare/native"]
test-stubs = ["native", "appd-bare/test-stubs"]

[dependencies]
appd-bare = { path = "../appd-bare", optional = true }
appd-bundle = { path = "../appd-bundle", optional = true }
rcgen = { workspace = true, features = ["pem", "x509-parser"] }
thiserror.workspace = true
time.workspace = true
x509-parser = { workspace = true, features = ["verify"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
